type Appearance = struct {
  head_index: u16,
  hat_index: u16,
  body_index: u16,
  accessory_index: u16,
  body_color: str,
  back_color: str,
};

constructor {
  New : ();
};

service Warrior {
  query GetAppearance : () -> Appearance;
  query GetOwner : () -> actor_id;
};

