import backgroundSvg from './background.svg';
import timerLightSvg from './timer-light.svg';
export { timerLightSvg };
export { backgroundSvg };
export { default as AdminIcon } from './icons/admin.svg?react';
export { default as SearchIcon } from './icons/search.svg?react';
export { default as CodeSlashIcon } from './icons/code-slash.svg?react';
export { default as ArrowRightIcon } from './icons/arrow-right.svg?react';
export { default as MagicLineIcon } from './icons/magic-line.svg?react';
export { default as HealthIcon } from './icons/health.svg?react';
export { default as AttackIcon } from './icons/attack.svg?react';
export { default as DefenceIcon } from './icons/defence.svg?react';
export { default as AttackButtonIcon } from './icons/attack-button.svg?react';
export { default as DefenceButtonIcon } from './icons/defence-button.svg?react';
export { default as UltimateButtonIcon } from './icons/ultimate-button.svg?react';
export { default as DodgeIcon } from './icons/dodge.svg?react';
export { default as CopyIcon } from './icons/copy.svg?react';
export { default as InfoIcon } from './icons/info.svg?react';
export { default as GameButtonGlowSvg } from './icons/game-button-glow.svg?react';
export { default as LoaderIcon } from './icons/loader.svg?react';
export { default as UserSmileIcon } from './icons/user-smile.svg?react';
export { default as UserSkullIcon } from './icons/user-skull.svg?react';
export { default as SkullBigIcon } from './icons/skull-big.svg?react';
export { default as CupStarIcon } from './icons/cup-star.svg?react';
export { default as CaretRightIcon } from './icons/caret-right.svg?react';
export { default as FilledCrossIcon } from './icons/filled-cross.svg?react';
export { default as ExitIcon } from './icons/exit.svg?react';
export * from './character';
