type PlayerInfo = struct {
  position: u8,
  balance: u32,
  debt: u32,
  in_jail: bool,
  round: u128,
  cells: vec u8,
  penalty: u8,
  lost: bool,
};

type Gear = enum {
  Bronze,
  Silver,
  Gold,
};

constructor {
  New : ();
};

service Player {
  query YourTurn : (players: vec struct { actor_id, PlayerInfo }, properties: vec opt struct { actor_id, vec Gear, u32, u32 }) -> bool;
};

