import backgroundSvg from './background.svg';
import timerLightSvg from './timer-light.svg';
export { timerLightSvg };
export { backgroundSvg };
export { ReactComponent as AdminIcon } from './icons/admin.svg';
export { ReactComponent as SearchIcon } from './icons/search.svg';
export { ReactComponent as CodeSlashIcon } from './icons/code-slash.svg';
export { ReactComponent as ArrowRightIcon } from './icons/arrow-right.svg';
export { ReactComponent as MagicLineIcon } from './icons/magic-line.svg';
export { ReactComponent as HealthIcon } from './icons/health.svg';
export { ReactComponent as AttackIcon } from './icons/attack.svg';
export { ReactComponent as DefenceIcon } from './icons/defence.svg';
export { ReactComponent as AttackButtonIcon } from './icons/attack-button.svg';
export { ReactComponent as DefenceButtonIcon } from './icons/defence-button.svg';
export { ReactComponent as UltimateButtonIcon } from './icons/ultimate-button.svg';
export { ReactComponent as DodgeIcon } from './icons/dodge.svg';
export { ReactComponent as CopyIcon } from './icons/copy.svg';
export { ReactComponent as InfoIcon } from './icons/info.svg';
export { ReactComponent as GameButtonGlowSvg } from './icons/game-button-glow.svg';
export { ReactComponent as LoaderIcon } from './icons/loader.svg';
export { ReactComponent as UserSmileIcon } from './icons/user-smile.svg';
export { ReactComponent as UserSkullIcon } from './icons/user-skull.svg';
export { ReactComponent as SkullBigIcon } from './icons/skull-big.svg';
export { ReactComponent as CupStarIcon } from './icons/cup-star.svg';
export { ReactComponent as CaretRightIcon } from './icons/caret-right.svg';
export * from './character';
