export { ReactComponent as PolkadotSVG } from './polkadot.svg'
export { ReactComponent as SubWalletSVG } from './subwallet.svg'
export { ReactComponent as TalismanSVG } from './talisman.svg'
export { ReactComponent as EnkryptSVG } from './enkrypt.svg'
export { ReactComponent as ExitSVG } from './exit.svg'
export { ReactComponent as NovaIcon } from './nova.svg'
