export { default as CrossIcon } from './icons/cross.svg?react';
export { default as GearIcon } from './icons/gear.svg?react';
export { default as TwitterIcon } from './icons/twitter.svg?react';
export { default as GithubIcon } from './icons/github.svg?react';
export { default as DiscordIcon } from './icons/discord.svg?react';
export { default as MediumIcon } from './icons/medium.svg?react';
export { default as VaraLogoIcon } from './icons/vara-logo.svg?react';
export { default as ChevronDown } from './icons/chevron-down.svg?react';
export { default as ChevronLeft } from './icons/chevron-left.svg?react';
export { default as ChevronsLeft } from './icons/chevrons-left.svg?react';
export { default as ChevronRight } from './icons/chevron-right.svg?react';
export { default as ChevronsRight } from './icons/chevrons-right.svg?react';
export { default as CaretDown } from './icons/caret-down.svg?react';
export { default as CopyDecoded } from './icons/copy-decoded.svg?react';
export { default as EditIcon } from './icons/edit.svg?react';
export { default as BurgerMenuIcon } from './icons/burger-menu.svg?react';
export { default as DefaultAvatar } from './icons/default-avatar.svg';
export { default as AllInIcon } from './icons/button-all-in.svg?react';
export { default as CallIcon } from './icons/button-call.svg?react';
export { default as FoldIcon } from './icons/button-fold.svg?react';
export { default as Chips2xIcon } from './icons/chips-2x.svg?react';
export { default as Chips3xIcon } from './icons/chips-3x.svg?react';
export { default as Chips5xIcon } from './icons/chips-5x.svg?react';
export { default as BannerLock } from './banner-lock.svg?react';
export { default as BannerSuits } from './banner-suits.png';
export { default as CreateGameIllustration } from './create-game-illustration.png';
export { default as JoinGameIllustration } from './join-game-illustration.png';

export * from './icons/cards';

export { default as OnboardingLockIcon } from './onboarding-lock.svg';
export { default as OnboardingCardsIcon } from './onboarding-cards.svg';
export { default as OnboardingBlackjackIcon } from './onboarding-blackjack.png';
