# Build stage
FROM node:18-alpine AS build

WORKDIR /opt/fe

COPY . /opt/fe

ARG REACT_APP_NODE_ADDRESS \
    REACT_APP_DEFAULT_NODES_URL \
    REACT_APP_IPFS_ADDRESS \
    REACT_APP_IPFS_GATEWAY_ADDRESS \
    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS \
    REACT_APP_DEFAULT_CONTRACT_ADDRESS \
    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS

ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
    REACT_APP_DEFAULT_NODES_URL=${REACT_APP_DEFAULT_NODES_URL} \
    REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
    REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS} \
    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS=${REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS} \
    REACT_APP_DEFAULT_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_CONTRACT_ADDRESS} \
    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS} \
    DISABLE_ESLINT_PLUGIN=true

RUN apk update --no-cache && \
    apk add --no-cache xsel && \
    yarn install && \
    yarn build && \
    rm -rf /var/cache/apk/*

# Run stage
FROM node:18-alpine

WORKDIR /opt/fe

COPY . /opt/fe
COPY --from=build /opt/fe/dist /opt/fe/dist
COPY --from=build /opt/fe/node_modules /opt/fe/node_modules

ARG REACT_APP_NODE_ADDRESS \
    REACT_APP_DEFAULT_NODES_URL \
    REACT_APP_IPFS_ADDRESS \
    REACT_APP_IPFS_GATEWAY_ADDRESS \
    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS \
    REACT_APP_DEFAULT_CONTRACT_ADDRESS \
    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS

ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
    REACT_APP_DEFAULT_NODES_URL=${REACT_APP_DEFAULT_NODES_URL} \
    REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
    REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS} \
    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS=${REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS} \
    REACT_APP_DEFAULT_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_CONTRACT_ADDRESS} \
    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS} \
    DISABLE_ESLINT_PLUGIN=true

RUN npm install --global serve

CMD ["serve", "-s", "/usr/src/build"]
