name: Contracts CI

on:
  pull_request:
    paths: contracts/**
  push:
    paths: contracts/**
    branches: [master]
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

env:
  CARGO_TERM_COLOR: always
  IMAGE_PREFIX: gear-contracts
  REGISTRY: ghcr.io/${{ github.repository }}

defaults:
  run:
    working-directory: contracts

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepair:
    if: github.ref == 'refs/heads/di-contract-dockerfile' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image.outputs.image_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch
        id: branch
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Get short SHA
        id: sha
        run: |
          sha_short=$(git rev-parse --short HEAD)
          echo "sha_short=$sha_short" >> $GITHUB_ENV

      - name: Set IMAGE_NAME
        id: image
        run: |
          image_name=${{ env.REGISTRY }}-${{ env.IMAGE_PREFIX}}:${{ env.branch_name }}
          echo "image_name=$image_name" >> $GITHUB_OUTPUT

  build_image:
    if: github.ref == 'refs/heads/di-contract-dockerfile' && github.ref_type == 'tag'
    needs: [prepair]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: contracts
          file: Dockerfile
          push: true
          tags: ${{ needs.prepair.outputs.image_name }}

  all:
    name: All
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: ${{ github.ref_type == 'tag' && 'Build' || 'Build & CI' }}
        run: '[ $GITHUB_REF_TYPE = "tag" ] && cargo b || cargo xtask ci'

      - name: Update the nightly tag
        if: github.ref == 'refs/heads/master'
        run: |
          git tag nightly
          git push -f origin nightly

      - name: Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref == 'refs/heads/master' && 'Nightly' || github.ref_name }}
          tag_name: ${{ github.ref == 'refs/heads/master' && 'nightly' || github.ref_name }}
          prerelease: ${{ github.ref == 'refs/heads/master' }}
          files: |
            contracts/target/wasm32-unknown-unknown/debug/*.*.wasm
            contracts/target/wasm32-unknown-unknown/debug/*.meta.txt

      - name: Upload the GitHub Pages artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: contracts/target/doc

  # A separate job for the Pages deployment is neccessary to prevent the spam from the "deployed"
  # messages in PRs.
  # https://github.com/orgs/community/discussions/36919
  deploy:
    name: Deploy GitHub Pages
    if: github.ref == 'refs/heads/master'
    needs: all
    environment: github-pages
    runs-on: self-hosted
    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
